<?php

return [
    'general' => [
        'app_name' => env('APP_NAME', 'NexusERP'),
        'app_description' => 'Enterprise Resource Planning System',
        'app_logo' => env('APP_LOGO', ''),
        'app_favicon' => env('APP_FAVICON', ''),
        'timezone' => env('APP_TIMEZONE', 'UTC'),
        'date_format' => env('APP_DATE_FORMAT', 'Y-m-d'),
        'time_format' => env('APP_TIME_FORMAT', 'H:i:s'),
        'datetime_format' => env('APP_DATETIME_FORMAT', 'Y-m-d H:i:s'),
        'default_language' => env('APP_LOCALE', 'en'),
        'maintenance_mode' => (bool) env('APP_MAINTENANCE_MODE', false),
        'maintenance_message' => env('APP_MAINTENANCE_MESSAGE'),
    ],

    'company' => [
        'company_name' => env('COMPANY_NAME', 'Your Company Name'),
        'company_registration_number' => env('COMPANY_REGISTRATION_NUMBER'),
        'company_tax_number' => env('COMPANY_TAX_NUMBER'),
        'company_phone' => env('COMPANY_PHONE'),
        'company_email' => env('MAIL_FROM_ADDRESS', 'admin@example.com'),
        'company_website' => env('COMPANY_WEBSITE'),
        'company_address_line_1' => env('COMPANY_ADDRESS_LINE_1'),
        'company_address_line_2' => env('COMPANY_ADDRESS_LINE_2'),
        'company_city' => env('COMPANY_CITY'),
        'company_state' => env('COMPANY_STATE'),
        'company_postal_code' => env('COMPANY_POSTAL_CODE'),
        'company_country' => env('COMPANY_COUNTRY', 'MY'),
        'company_logo' => env('COMPANY_LOGO'),
        'company_description' => env('COMPANY_DESCRIPTION'),
    ],

    'financial' => [
        'default_currency' => env('APP_DEFAULT_CURRENCY', 'USD'),
        'currency_symbol' => env('APP_CURRENCY_SYMBOL', '$'),
        'currency_position' => env('APP_CURRENCY_POSITION', 'before'),
        'decimal_places' => (int) env('APP_DECIMAL_PLACES', 2),
        'decimal_separator' => env('APP_DECIMAL_SEPARATOR', '.'),
        'thousands_separator' => env('APP_THOUSANDS_SEPARATOR', ','),
        'default_tax_rate' => (float) env('APP_DEFAULT_TAX_RATE', 0.00),
        'tax_inclusive_pricing' => (bool) env('APP_TAX_INCLUSIVE_PRICING', false),
        'financial_year_start' => env('APP_FINANCIAL_YEAR_START', '01-01'),
        'invoice_prefix' => env('APP_INVOICE_PREFIX', 'INV-'),
        'quote_prefix' => env('APP_QUOTE_PREFIX', 'QUO-'),
        'purchase_order_prefix' => env('APP_PURCHASE_ORDER_PREFIX', 'PO-'),
        'invoice_number_length' => (int) env('APP_INVOICE_NUMBER_LENGTH', 6),
        'auto_invoice_numbering' => (bool) env('APP_AUTO_INVOICE_NUMBERING', true),
    ],

    'uom' => [
        'default_weight_unit' => env('APP_DEFAULT_WEIGHT_UNIT', 'KG'),
        'default_length_unit' => env('APP_DEFAULT_LENGTH_UNIT', 'M'),
        'default_volume_unit' => env('APP_DEFAULT_VOLUME_UNIT', 'L'),
        'default_area_unit' => env('APP_DEFAULT_AREA_UNIT', 'M2'),
        'default_temperature_unit' => env('APP_DEFAULT_TEMPERATURE_UNIT', 'C'),
        'enable_compound_units' => (bool) env('APP_ENABLE_COMPOUND_UNITS', true),
        'enable_custom_units' => (bool) env('APP_ENABLE_CUSTOM_UNITS', true),
        'auto_convert_units' => (bool) env('APP_AUTO_CONVERT_UNITS', false),
        'conversion_precision' => (int) env('APP_CONVERSION_PRECISION', 4),
        'show_unit_codes' => (bool) env('APP_SHOW_UNIT_CODES', true),
        'show_unit_names' => (bool) env('APP_SHOW_UNIT_NAMES', true),
    ],

    'notifications' => [
        'email_notifications' => (bool) env('APP_EMAIL_NOTIFICATIONS', true),
        'sms_notifications' => (bool) env('APP_SMS_NOTIFICATIONS', false),
        'browser_notifications' => (bool) env('APP_BROWSER_NOTIFICATIONS', true),
        'notify_on_low_inventory' => (bool) env('APP_NOTIFY_LOW_INVENTORY', true),
        'notify_on_order_updates' => (bool) env('APP_NOTIFY_ORDER_UPDATES', true),
        'notify_on_payment_received' => (bool) env('APP_NOTIFY_PAYMENT_RECEIVED', true),
        'notify_on_invoice_overdue' => (bool) env('APP_NOTIFY_INVOICE_OVERDUE', true),
        'notify_on_system_errors' => (bool) env('APP_NOTIFY_SYSTEM_ERRORS', true),
        'admin_email' => env('APP_NOTIFICATIONS_ADMIN_EMAIL', env('MAIL_FROM_ADDRESS', 'admin@example.com')),
        'admin_phone' => env('APP_NOTIFICATIONS_ADMIN_PHONE'),
        'notification_batch_size' => (int) env('APP_NOTIFICATION_BATCH_SIZE', 50),
        'notification_frequency' => env('APP_NOTIFICATION_FREQUENCY', 'immediate'),
    ],
];
